data:
  build: ./data
  volumes: 
    - "/c/Users/elick/myapp:/data"
    
mysql:
  build: ./mysql
  volumes_from:
    - data
  volumes: 
    - "/c/Users/elick/myapp/db/mysql:/var/lib/mysql"
  environment:
    - MYSQL_ROOT_PASSWORD=123456
  ports:
    - "3306:3306"
php:  
  build: ./php
  expose:
    - "9000"
  volumes_from:
    - data
  links:
    - mysql
  privileged: true

nginx:  
  build: ./nginx
  volumes_from:
    - data
  volumes:
    - "/c/Users/elick/myapp/nginx/nginx.conf:/etc/nginx/nginx.conf"
  links:
    - php:php
  ports:
    - "80:80"
  privileged: true