mysql:
  build: ./mysql
  volumes_from:
    - myapp-data
  environment:
        - MYSQL_ROOT_PASSWORD=123456
php:  
  build: ./php
  ports:
    - "9000:9000"
  volumes_from:
    - myapp-data
  links:
    - mysql
  privileged: true

nginx:  
  build: ./nginx
  volumes_from:
    - myapp-data
  links:
    - php:php
  ports:
    - "80:80"
  privileged: true